import re
from typing import List

from app.domain.schemas import QuestionResponse
from app.domain.document_models import StoredChunk


def normalize_for_citation(text: str) -> str:
    if not text:
        return ""
    # Remove punctuation, newlines, and extra whitespace for robust matching
    text = re.sub(r'[\W_]+', ' ', text)
    return text.lower().strip()

class CitationValidationService:
    def validate_citations(self, response: QuestionResponse, chunks: List[StoredChunk]) -> QuestionResponse:
        """
        Validates that the citations generated by the LLM actually exist in the document.
        """
        valid_citations = []
        for citation in response.citations:
            is_valid = False
            norm_citation = normalize_for_citation(citation.source_text)
            
            print(f"DEBUG CITATION: {norm_citation}")
            
            if not norm_citation:
                continue
                
            for chunk in chunks:
                norm_chunk = normalize_for_citation(chunk.source_text)
                if norm_citation in norm_chunk:
                    print(f"DEBUG MATCHED CHUNK: {norm_chunk}")
                    citation.chunk_id = chunk.chunk_id
                    citation.page = chunk.page_start
                    citation.clause_number = chunk.clause_number
                    is_valid = True
                    break
            
            if not is_valid:
                print(f"DEBUG FAILED TO MATCH CITATION: {norm_citation}")
            
            if is_valid:
                valid_citations.append(citation)

        # If citations were provided but none were valid, reject the answer
        if response.citations and not valid_citations:
            response.status = "CITATION_VALIDATION_FAILED"
            response.answer_type = "NOT_FOUND"
            response.confidence = "low"
            response.citations = []
            response.answer = "I cannot find sufficient evidence in the document to answer this question accurately."
        else:
            response.citations = valid_citations

        return response
